### ISSUE TITLE
[Pokemon Color Variants] SystemStackError

### ISSUE THREAD

**Issue by gaiawindwave90** [MickTK/Essentials-Plugins#1]
I got an error when I got Mudkip when Pokemon Color Variants is installed

"=================

[2023-02-22 20:29:17 -0500]
[Pokémon Essentials version 20.1]
[v20.1 Hotfixes 1.0.7]

Script error in event 6 (coords 10,4), map 4 (Pokémon Lab)
Exception: SystemStackError
Message: stack level too deep

***Full script:
pkmn = Pokemon.new(:MUDKIP, 5)
pkmn.item = :ORANBERRY
pkmn.shiny = false
pkmn.calc_stats
pbAddPokemon(pkmn)

Backtrace:
[Pokemon Color Variants] Pokemon.rb:10:in `initialize'
[Pokemon Color Variants] Pokemon.rb:10:in `initialize'
[Pokemon Color Variants] Pokemon.rb:10:in `initialize'
[Pokemon Color Variants] Pokemon.rb:10:in `initialize'
[Pokemon Color Variants] Pokemon.rb:10:in `initialize'
[Pokemon Color Variants] Pokemon.rb:10:in `initialize'
[Pokemon Color Variants] Pokemon.rb:10:in `initialize'
[Pokemon Color Variants] Pokemon.rb:10:in `initialize'
[Pokemon Color Variants] Pokemon.rb:10:in `initialize'
[Pokemon Color Variants] Pokemon.rb:10:in `initialize'"

Please fix it

**Comment by MickTK** [comment]
There is no `Pokemon.rb` in the current version.

The error should be fixed updating the plugin:
1. Delete the old `Plugins/Pokemon Color Variants` folder.
2. Download and install the [latest version](https://github.com/MickTK/Pokemon-Essentials-Plugins/tree/main/Pokemon%20Color%20Variants).
